### ISSUE TITLE
Delay in interrupt service routine might be an issue

### ISSUE THREAD

**Issue by Kai2c** [DeverSean/lamppedal#1]
I didn't look too deep into this, but might be an issue if this delay for the Triac is blocking the next ADC reading

https://github.com/DeverSean/lamppedal/blob/15236bbabfcb5da395aaa231b75b33125ca35d07/Core/Src/main.c#L323C7-L323C44

**Comment by DeverSean** [comment]
adcval_to_us() converts the raw adc value (max 4096) to a microsecond value (max 8333). Since there is only a zero crossing every 8333us, the delay should never block the ADC recognizing the next zero crossing. Eventually, the delay should be replaced with a timer interrupt thing so we aren't blocking all the other stuff we want to be doing between zero crossings. For now, I'm just trying to make sure the zero crossing and triac circuits actually work. 

Lmk if all that makes sense and addresses your concern.

**Comment by DeverSean** [comment]
I updated adcval_to_us() to be more readable, it was functional but wonky before with some unnecessary bit shifting.
